---
version: "2.1"
services:
  fancontrol:
    image: mathsterk/fancontrol
    container_name: fancontrol
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
